name: Auto Deploy
on:
  push:
    branches:
      - main
    paths:
      - 'webHelpKR2.zip'
      - 'webHelpImages.zip'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3
      
      # 上传 webHelpKR2.zip 到服务器
      - name: Upload webHelpKR2.zip to server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          source: "./webHelpKR2.zip"  # 本地 webHelpKR2.zip 文件的路径
          target: "/var/www/docs/kotlin/"  # 服务器上存放 webHelpKR2.zip 的目录
      
      # 解压 webHelpKR2.zip 文件
      - name: Unzip webHelpKR2.zip on server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/docs/kotlin/
            unzip -o webHelpKR2.zip
            rm webHelpKR2.zip
      
      # 上传 B.zip 到服务器
      - name: Upload webHelpImages.zip to server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          source: "./webHelpImages.zip"  # 本地 webHelpImages.zip 文件的路径
          target: "/var/www/docs/kotlin/"  # 服务器上存放 webHelpImages.zip 的目录
      
      # 解压 webHelpImages.zip 文件
      - name: Unzip webHelpImages.zip on server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/docs/kotlin/
            unzip -o webHelpImages.zip -d ./images/
            rm webHelpImages.zip  # 可选：解压完成后删除 B.zip 文件
